command_timeout = 1000
add_newline = false

format = """
$hostname\
$os\
$directory\
$git_branch\
$git_status \
$python\
$aws\
$golang\
$java\
$c\
$nodejs\
$rust\
$ruby\
$scala\
$dart\
$conda\
$pijul_channel\
$lua\
$rlang\
$buf\
$memory_usage\
$docker_context\
[](#1C3A5E)$time[ ](#1C3A5E)$cmd_duration
[|](bold green)
[└─ $shell> ](bold green)

"""

continuation_prompt = '▶▶ '

[shell]
disabled = false
bash_indicator = ""

[time]
disabled = false
time_format = "%r"
use_12hr = true
style = "bg:#1d2230"
format = '[[ 󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'

[cmd_duration]
format = 'last command: [$duration](bold yellow)'

# ---

[os]
format = '[$symbol](bold white) '   
disabled = false

[os.symbols]
Arch = '' 

# Shows the hostname
[hostname]
ssh_only = true
format = " "
disabled = false

# Shows current directory
[directory]
truncation_length = 1
fish_style_pwd_dir_length=2
truncation_symbol = '…/'
home_symbol = '[󰋜:~'
read_only_style = '197'
read_only = ' '
format = '[$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
[git_branch]
symbol = "  "
format = '[$symbol$branch]($style)'
truncation_length = 4
truncation_symbol = '…/'
style = 'bold green'

# Shows current git status
[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold green'
conflicted = ''
up_to_date = ''
untracked = ' '
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = ' 󰏖'
modified = '  '
staged = '[++\($count\)](green)'
renamed = '󰑕 '
deleted = ' '


# ---

[aws]
symbol = ""

[buf]
symbol = ""

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "
disabled = true
style='bold dimmed white'
threshold = 1
format = "$symbol [${ram}(|${swap})]($style) "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "
pyenv_version_name = true

[ruby]
symbol = " "

[rlang]
symbol = "󰟔 "

[rust]
symbol = " "

[scala]
symbol = " "
